export const huaweimodels = [
	{ key: '37',
		model : 'Mate 9',
		modelNum: 'MHA-L09',
		screenrep: '150.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'85.00',
	  volumerep:null,
	  battrep:'60.00',
		signalrep:null,
		backglassrep: null,
	
	
	},

	{ key:'38',
		model : 'P10',
		modelNum: 'VTR-AL00',
		screenrep: '150.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,
	},

	{ key:'39',
		model : 'P10 Lite',
		modelNum: 'WAS-LX1A',
		screenrep: '115.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'85.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,
	},

	{ key:'40',
		model : 'P9',
		modelNum: 'EVA-L09',
		screenrep: '125.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

	{ key:'41',
		model : 'P9 Lite',
		modelNum: 'VNS-L31',
		screenrep: '115.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'85.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

	{ key:'42',
		model : 'P8',
		modelNum: 'GRA-L09',
		screenrep: '105.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'85.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

	{ key:'43',
		model : 'P8 Lite (2017)',
		modelNum: 'PRA-LA1',
		screenrep: '115.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'85.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

	{ key:'44',
		model : 'P8 Lite (2016)',
		modelNum: 'ALE-L21',
		screenrep: '105.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'75.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

	{ key:'45',
		model : 'P7',
		modelNum: 'P7-L10/P7-L00',
		screenrep: '105.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'75.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'80.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: null,},

];