export const huaweitablet = [
  { model: 'MediaPad T5',
	modelNum : 'AGS2-L09',
	screenrep: '550.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'175.00',
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'120.00',
	volumerep:null,
	battrep:'95.00',
	signalrep:null,
	backglassrep: '100.00',
},

  { model: 'MediaPad M3 Lite',
	modelNum : 'CPN-AL00',
	screenrep: '550.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'175.00',
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'120.00',
	volumerep:null,
	battrep:'95.00',
	signalrep:null,
	backglassrep: '100.00',
},

{ model: 'MediaPad M3 Lite 10',
  modelNum : 'Bach-W01',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad M3',
  modelNum : 'BTV-DL09',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad T3 10',
  modelNum : 'AGS-L03',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad T3 7 3G',
  modelNum : 'BG2-U01',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad T2 7.0',
  modelNum : 'BGO-DL09',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad M5 8.4 inches',
  modelNum : 'SHT-AL09',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad M5 10.8 inches',
  modelNum : 'CMR-AL09',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: 'MediaPad M5 Pro',
  modelNum : 'CMR-AL19',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},

{ model: ' MediaPad M5 Lite',
  modelNum : 'BAH2-L09',
  screenrep: '550.00',
  headphonerep:null,
  earpiecerep:null,
  powerrep:null,
  rearcamrep:'175.00',
  frontcamrep:'85.00',
  homerep:null,
  upmicrep:null,
  chargeportrep:'120.00',
  volumerep:null,
  battrep:'95.00',
  signalrep:null,
  backglassrep: '100.00',

},
]