export const laptoprepairs = [
	{ repair : 'Screen Replacement',
	  price:'75.00'},
	{ repair : 'Keyboard Replacement',
	price:'75.00'},
	{ repair : 'Fan Replacement', price:'75.00'},
	{ repair : 'Camera Repair', price:'75.00'},
	{ repair : 'Speaker Repair', price:'75.00'},
	{ repair : 'Charging Port Repair', price:'75.00'},
	{ repair : 'Data Recovery', price:'129.00'},
	{ repair : 'Battery Replacement', price:'75.00'},
	{ repair : 'Virus Removal with 1 free year of Anti-Virus Software', price:'140.00'},
	{ repair : 'Hard Drive Replacement - 50GB HDD (Operating System Reinstall)', price:'150.00'},
	{ repair : 'Hard Drive Replacement - 1TB HDD (Operating System Reinstall)', price:'195.00'},
	{ repair : 'Hard Drive Replacement - 50GB SSD (Operating System Reinstall)', price:'250.00'},
	{ repair : 'Hard Drive Replacement - 1TB SSD (Operating System Reinstall)', price:'300.00'},
	{ repair : 'Hard Drive Replacement - 50GB HDD (Operating System & Data Transfer)', price:'200.00'},
	{ repair : 'Hard Drive Replacement - 1TB HDD (Operating System & Data Transfer)', price:'250.00'},
	{ repair : 'Hard Drive Replacement - 50GB SSD (Operating System & Data Transfer)', price:'320.00'},
	{ repair : 'Hard Drive Replacement - 1TB SSD (Operating System & Data Transfer)', price:'370.00'},
];