export const laptoprepairs = [
	{ repair : 'Laptop Screen Replacement',
	  price:'75.00',
		deposit: '€75.00 Deposit Required'},
	{ repair : 'Keyboard Replacement',
	price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Fan Replacement', price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Laptop Camera Repair', price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Laptop Speaker Repair', price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Laptop Charging Port Repair', price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Data Recovery', price:'129.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Battery Replacement', price:'75.00',
	deposit: '€75.00 Deposit Required'},
	{ repair : 'Virus Removal with 1 free year of Anti-Virus Software', price:'155.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 500GB HDD (Operating System Reinstall)', price:'150.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 1TB HDD (Operating System Reinstall)', price:'215.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 500GB SSD (Operating System Reinstall)', price:'275.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 1TB SSD (Operating System Reinstall)', price:'320.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 500GB HDD (Operating System & Data Transfer)', price:'230.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 1TB HDD (Operating System & Data Transfer)', price:'275.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 500GB SSD (Operating System & Data Transfer)', price:'335.00',
	deposit: ''},
	{ repair : 'Hard Drive Replacement - 1TB SSD (Operating System & Data Transfer)', price:'395.00',
	deposit: ''},
];