export const laptopbrands = [
	{ 	key:'6',
		brand: 'Hewlett Packard (HP)' },
	{ 	key:'2',
		brand: 'Levono' },
	{ 	key:'3',
		brand: 'Dell' },
	{ 	key:'6',
		brand: 'Asus' },
	{ 	key:'2',
		brand: 'Acer' },
	{ 	key:'3',
		brand: 'Microsoft' },
	{ 	key:'6',
		brand: 'Samsung' },
	{ 	key:'2',
		brand: 'Sony' },
	{ 	key:'3',
		brand: 'Google Chromebook' },
	{ 	key:'3',
		brand: 'Toshiba' },
	{ 	key:null,
		brand: 'Other' },

]