export const laptopbrands = [
	{ 	key:'7',
		brand: 'Hewlett Packard (HP)' },
	{ 	key:'8',
		brand: 'Lenovo' },
	{ 	key:'9',
		brand: 'Dell' },
	{ 	key:'10',
		brand: 'Asus' },
	{ 	key:'11',
		brand: 'Acer' },
	{ 	key:'12',
		brand: 'Microsoft' },
	{ 	key:'2',
		brand: 'Samsung' },
	{ 	key:'4',
		brand: 'Sony' },
	{ 	key:'13',
		brand: 'Google Chromebook' },
	{ 	key:'14',
		brand: 'Toshiba' },
	{ 	key:null,
		brand: 'Other' },

]