export const networks = [
	{	key:'1',
		network : 'Unlocked'},
	{	key:'2', 
		network : 'Vodafone'},
	{	key:'3', 
		network : 'O2'},
	{	key:'4', 
		network : 'Three'},
	{	key:'5', 
		network : 'Tesco'},
	{	key:'6', 
		network : 'Eir'},
	// {	key:null, 
	// 	network : 'Other'},
];