export const nokiamodels = [
  { 
		key:'54',
		model : 'Lumia 640', 
	modelNum : 'RM-1073',
	screenrep: '95.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'75.00',
	frontcamrep:'75.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'75.00',
	volumerep:null,
	battrep:'75.00',
	signalrep:null,
	backglassrep: '75.00',},

  { 
		key:'55',
		model : 'Lumia 820', 
	modelNum : 'RM-824',
	screenrep: '140.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'85.00',
	frontcamrep:null,
	homerep:null,
	upmicrep:null,
	chargeportrep:'75.00',
	volumerep:null,
	battrep:'75.00',
	signalrep:null,
	backglassrep: '75.00',



},
  { 
		key:'56',
		model : 'Lumia 920', 
	modelNum : 'RM-820',
	screenrep: '125.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'95.00',
	frontcamrep:'95.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'95.00',
	volumerep:null,
	battrep:'75.00',
	signalrep:null,
	backglassrep: '75.00',


},
  { 
		key:'57',
		model : 'Nokia 6', 
	modelNum : 'TA-1021',
	screenrep: '145.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'75.00',
	frontcamrep:'95.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'90.00',
	volumerep:null,
	battrep:'65.00',
	signalrep:null,
	backglassrep: null,

},
  { 
		key:'58',
		model : 'Nokia 7', 
	modelNum : 'TA-1041',
	screenrep: '320.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:null,
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'145.00',
	volumerep:null,
	battrep:'75.00',
	signalrep:null,
	backglassrep: null,},
	
  { 
		key:'59',
		model : 'Nokia 8', 
	modelNum : 'TA-1012',
	screenrep: '275.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:null,
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'170.00',
	volumerep:null,
	battrep:'95.00',
	signalrep:null,
	backglassrep: null,
}
	

];