export const samsungmodels = [
	{ key:'14',
		model : 'Galaxy S9', 
		modelNum : 'SM-G965', 
	  screenrep: '290.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'175.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
	  chargeportrep:'120.00',
	  volumerep:null,
	  battrep:'95.00',
		signalrep:null,
		backglassrep: '100.00',
	},

	{ key:'15',
		model : 'Galaxy S9 Plus', 
	  modelNum : 'SM-G9650', 
	  screenrep: '320.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'185.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'120.00',
	  volumerep:null,
	  battrep:'100.00',
		signalrep:null,
		backglassrep: '105.00',
	
	},

	{ key:'16',
		model : 'Galaxy S8', 
	  modelNum : 'SM-G950', 
	  screenrep: '275.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'110.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'115.00',
	  volumerep:null,
	  battrep:'85.00',
		signalrep:null,
		backglassrep: '85.00',
	},

	{ key:'17',
		model : 'Galaxy S8 Plus', 
	  modelNum : 'SM-G955', 
	  screenrep: '295.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'110.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'95.00',
		signalrep:null,
		backglassrep: '95.00',
	},

	{ key:'18',
		model : 'Galaxy S7', 
	  modelNum : 'SM-G930', 
	  screenrep: '190.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'110.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'80.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'19',
		model : 'Galaxy S6', 
		modelNum : 'SM-G920', 
		screenrep: '175.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'75.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: '65.00',

},

	{ key:'20',
		model : 'Galaxy S5', 
	  modelNum : 'SM-G900', 
	  screenrep: '130.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'75.00',
	  frontcamrep:'75.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: '75.00',
	
		
	},

	{ key:'21',
		model : 'Galaxy Note 8', 
	  modelNum : 'SM-N950', 
	  screenrep: '390.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'135.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'95.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'22',
		model : 'Galaxy Note 5', 
	  modelNum : 'SM-N920x', 
	  screenrep: '220.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'85.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'23',
		model : 'Galaxy A3 (2017)', 
	  modelNum : 'SM-A320', 
	  screenrep: '125.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'105.00',
	  frontcamrep:'75.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'95.00',
		signalrep:null,
		backglassrep: '55.00',
	
	
	},

	{ key:'24',
		model : 'Galaxy A3 (2016)', 
	  modelNum : 'SM-A310', 
	  screenrep: '125.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'75.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'99.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: '75.00',
	
	
	},

	{ key:'25',
		model : 'Galaxy A3 (2015)', 
	  modelNum : 'SM-A300', 
	  screenrep: '120.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'110.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'99.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '75.00',
	},

	{ key:'26',
		model : 'Galaxy A5 (2017)', 
	  modelNum : 'SM-A520', 
	  screenrep: '140.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'75.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '55.00',
	
	
	},

	{ key:'27',
		model : 'Galaxy A5 (2016)', 
	  modelNum : 'SM-A510', 
	  screenrep: '140.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'105.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'99.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'28',
		model : 'Galaxy A5 (2015)', 
	  modelNum : 'SM-A500', 
	  screenrep: '115.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'110.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'99.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '75.00',
	},

	{ key:'29',
		model : 'Galaxy A7 (2017)', 
	  modelNum : 'SM-A700H', 
	  screenrep: '165.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'115.00',
	  frontcamrep:'100.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'30',
		model : 'Galaxy J3 (2017)', 
	  modelNum : 'SM-J3300', 
	  screenrep: '165.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'105.00',
	  frontcamrep:'65.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'60.00',
		signalrep:null,
		backglassrep: '55.00',
	
	
	},

	{ key:'31',
		model : 'Galaxy J3 (2015)', 
	  modelNum : 'SM-J3109',
		screenrep: null,
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '75.00',
	
	
	
	
	},

	{ key:'32',
		model : 'Galaxy J5 (2017)', 
	  modelNum : 'SM-J530F', 	
		screenrep: '600.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'185.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'120.00',
	  volumerep:null,
	  battrep:'100.00',
		signalrep:null,
		backglassrep: '105.00',
	
	},

	{ key:'33',
		model : 'Galaxy J5 (2016)', 
	  modelNum : 'SM-J510', 
	 	screenrep: '110.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'95.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'70.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

	{ key:'34',
		model : 'Galaxy J5 (2015)', 
	  modelNum : 'SM-J500', 
	  screenrep: '99.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'85.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'95.00',
	  volumerep:null,
	  battrep:'75.00',
		signalrep:null,
		backglassrep: '75.00',
	
	
	},

	{ key:'35',
		model : 'Galaxy J7 (2017)', 
	  modelNum : 'SM-J730', 
	  screenrep: '145.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'85.00',
		signalrep:null,
		backglassrep: '75.00',
	
	
	},

	{ key:'36',
		model : 'Galaxy J7 (2016)', 
	  modelNum : 'SM-J710', 
	  screenrep: '110.00',
	  headphonerep:null,
	  earpiecerep:null,
	  powerrep:null,
		rearcamrep:'85.00',
	  frontcamrep:'95.00',
	  homerep:null,
	  upmicrep:null,
		chargeportrep:'110.00',
	  volumerep:null,
	  battrep:'85.00',
		signalrep:null,
		backglassrep: '75.00',
	
	},

];