export const sonymodels = [
  { model : 'Z3',
	modelNum: 'D6603',
	screenrep: '115.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'85.00',
	frontcamrep:'65.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'65.00',
	volumerep:null,
	battrep:'0.00',
	signalrep:null,
	backglassrep: '55.00',


},
  { model : 'Z3 Compact',
	modelNum: 'D5803',
	screenrep: '125.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'85.00',
	frontcamrep:'65.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'65.00',
	volumerep:null,
	battrep:'0.00',
	signalrep:null,
	backglassrep: '55.00',},

  { model : 'Z4',
	modelNum: 'unknown',
	screenrep: null,
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:null,
	frontcamrep:null,
	homerep:null,
	upmicrep:null,
	chargeportrep:null,
	volumerep:null,
	battrep:null,
	signalrep:null,
	backglassrep: null,
},

  { model : 'Z5',
	modelNum: ' E6603',
	screenrep: '135.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'100.00',
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'75.00',
	volumerep:null,
	battrep:'0.00',
	signalrep:null,
	backglassrep: '65.00',},

  { model : 'Z5 Compact',
	modelNum: 'E5803',
	screenrep: '145.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'100.00',
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'75.00',
	volumerep:null,
	battrep:'0.00',
	signalrep:null,
	backglassrep: '65.00',},

  { model : 'Z5 Premium',
	modelNum: 'E6853',
	screenrep: '150.00',
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:'100.00',
	frontcamrep:'85.00',
	homerep:null,
	upmicrep:null,
	chargeportrep:'85.00',
	volumerep:null,
	battrep:'0.00',
	signalrep:null,
	backglassrep: '65.00',},

  { model : 'X',
	screenrep: null,
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:null,
	frontcamrep:null,
	homerep:null,
	upmicrep:null,
	chargeportrep:null,
	volumerep:null,
	battrep:null,
	signalrep:null,
	backglassrep: null,},

  { model : 'XA',
	screenrep: null,
	headphonerep:null,
	earpiecerep:null,
	powerrep:null,
	rearcamrep:null,
	frontcamrep:null,
	homerep:null,
	upmicrep:null,
	chargeportrep:null,
	volumerep:null,
	battrep:null,
	signalrep:null,
	backglassrep: null,},

];